### ISSUE TITLE
Markdown Headers and Jekyll update

### ISSUE THREAD

**Issue by jhollist** [biouno/biouno.github.io#20]
@kinow Saw your site via https://github.com/ropensci/reproducibility-guide/issues/89

One thing I noticed is that your markdown headers didn't have spaces between the `#` and the text.  That was another thing that broke with the Jekyll update.  It needs a space to render as a header.  Caused me quite the headache on multiple sites!

**Comment by kinow** [comment]
Hi @jhollist 

Thanks for reporting the issue. Good catch!

Here's what I used to find what needed fixing.

```
grep -r -i --include \*.md --include \*.html -E "^#+[a-zA-Z0-9].*" *
```

**Comment by kinow** [comment]
Then you can play and get only unique file names.

```
grep -r -i --include \*.md --include \*.html -E "^#+[a-zA-Z0-9].*" * | awk -F: '{ print $1 }' | uniq
```

And then if that gives you the right files, you can automagically fix them with the following quick-and-dirty oneliner:

```
grep -r -i --include \*.md --include \*.html -E "^#+[a-zA-Z0-9].*" * | awk -F: '{ print $1 }' | uniq | xargs -I {} sed -i -e 's/^\(#\)\([a-zA-Z0-9]\)/\1 \2/' -e 's/^\(##\)\([a-zA-Z0-9]\)/\1 \2/' -e 's/^\(###\)\([a-zA-Z0-9]\)/\1 \2/' -e 's/^\(####\)\([a-zA-Z0-9]\)/\1 \2/' {}
```

**Comment by kinow** [comment]
And that seems to have fixed it. Thanks again @jhollist !!!

**Comment by jhollist** [comment]
No problem!  Happy to help.
