### ISSUE TITLE
Update website layout

### ISSUE THREAD

**Issue by kinow** [biouno/biouno.github.io#21]
This has been a topic in several of our hangouts. @imoutsatsos and myself discussed it and chose a couple of options (minimal-mistakes jekyll theme, and Groovy project web site).

I will start with minimal-mistakes, as our current site is using Jekyll, so it will be easier :-)

**Comment by kinow** [comment]
And giving back to the awesome theme project https://github.com/mmistakes/minimal-mistakes/pull/1104

**Comment by kinow** [comment]
@imoutsatsos finished updating the layout in the branch, to use the minimal styles jekyll theme. Easy-peasy to update the layout, without having to update existing documents. I believe we are also able to keep all previous URL's working, with no change.

https://kinow.github.io/index.html

For a preview version. Some links may be broken, but I've fixed them. Initially I had the same layout applied everywhere. But used the `splash` layout, that comes with the minimal mistakes theme. It does not display the menu, and instead we are supposed to sexy-up the landing page.

What do you think? Should we first finish this issue, migrating to a new theme, and later open a new ticket to update the landing page?

**Comment by imoutsatsos** [comment]
Great start @kinow ! Glad we will be able to reuse the content and links are preserved.
I have just started reviewing the [minimal mistakes layouts](https://mmistakes.github.io/minimal-mistakes/docs/layouts/) so I better understand what you said above. I agree the landing page should be a separate issue. Lots of possibilities!!

**Comment by kinow** [comment]
Great @imoutsatsos ! Let me know if you need any help, or if you would like a short hangout just for Jekyll. I have nothing planned this next Saturday morning, so happy to chat if you have some minutes on your Friday afternoon.

Can I submit a pull request for you to review/merge it, or do you prefer to change more things in the theme with minimal-mistakes, or maybe using another theme?

**Comment by imoutsatsos** [comment]
Let's keep this theme. It looks very nice. We just need to think how to enrich the landing page with some informative graphics/high level text relevant to the BioUno project goals. Let's think about that and chat perhaps this coming Fri/Sat

**Comment by kinow** [comment]
Good idea. If you find a figure, we can add it to the page by adding the following to the index.md file.

```
{% include figure image_path="/assets/img/top.jpg" alt="" caption="" %}
```

**Comment by kinow** [comment]
And there goes the PR :tada: 

https://github.com/biouno/biouno.github.io/pull/22

**Comment by imoutsatsos** [comment]
Preparing for review and just installed Jekyll on my Windows 10 !
![image](https://user-images.githubusercontent.com/3408226/28448489-656d1bd8-6da6-11e7-84d2-3dc2d4b26799.png)

**Comment by kinow** [comment]
Perfect! You should have ruby, gem, and bundler too. I think you shoul be able to

1. Clone website from my fork kinow/biouno.github.io
2. Check out the new layout branch
3. Install deps with bundle install
4. Start the site locally with jekyll s -w

**Comment by imoutsatsos** [comment]
Success! After a few tribulation with installing Ruby Gem dependencies I've got it build and running on my Windows 10 desktop

![image](https://user-images.githubusercontent.com/3408226/28461332-2326c7d6-6de4-11e7-9283-ce398b5688b6.png)

**Comment by kinow** [comment]
:tada" the `-w` stands for watch. It doesn't watch **every file**. But it does watch posts, pages... so if you change the markdown file, and reload the browser, it should work.

And if you have any improvements, I think you should be able to update that branch (if not I can enable that). Or we can merge first, and discuss enhancements later.

Anyway, talk to you soon :) (11:20 PM here)

**Comment by imoutsatsos** [comment]
@kinow I'm getting a deprecation warning during the Jekyll build:
Configuration file: /mnt/c/Users/Ioannis/gitrepos/biouno.github.io/_config.yml
       Deprecation: **The 'plugins' configuration option has been renamed to 'plugins_dir**'. Please update your config file accordingly.

**Comment by kinow** [comment]
Yup, I raised an issue and even submitted a pull request for that.

Actually, our Jekyll version is not the latest. They changed this option twice in the last releases (no idea why).

Ignore for now. Once Windows/Linux get the latest version of Jekyll (or if we install that manually) it will disappear.

**Comment by kinow** [comment]
Let's close it for now and open new issues for each customization, as necessary.
