### ISSUE TITLE
Add a tutorials section in the side menu

### ISSUE THREAD

**Issue by kinow** [biouno/biouno.github.io#26]

**Comment by kinow** [comment]
Not so easy to make it dynamic @imoutsatsos . But I think the current layout with the sidebar always being displayed could be enough? It contains the link to the tutorials as well. WDYT?

**Comment by imoutsatsos** [comment]
I agree @kinow . The landing page with the sidebar displayed is much better now. Thank you!

I don't think a 'Tutorials' section will need to be dynamically generated. It would be similar to the current 'Documentation' section which, if I'm not mistaken, is manually maintained. I'm assuming that the number of tutorials will be relatively small to make this manual updates feasible.

**Comment by kinow** [comment]
Having the tutorials as a main section in the side bar, like DOCUMENTATION sounds like a good idea! And I thought it was going to be easy... but after looking at the existing tutorials, you will notice the tutorials like takes you to a page with all the tutorials.

Some tutorials are about R plug-in, others about Active choices, and others about Image galleries.

I think if we had a page for each plug-in, and perhaps another page for Jenkins plug-ins, and then maybe in the future a page for things like IIIF; then we could add a section to the sidebar, and put the links to these pages under it.

Right now, I think the entries would be too specific to a certain plug-in, and with a link too long.

So, IMO, we could either re-think the current page of tutorials first, or just move the tutorials out of DOCUMENTATION, and make a TUTORIALS section/link... or leave as is for now.

Any thoughts @imoutsatsos ?

**Comment by imoutsatsos** [comment]
OK, so let me read it back to you! We put on the side bar something like:

TUTORIALS
   >Active-Choices
   >R-Plugin
   >Science-Plugins
   >Jenkins-Data Science
  > iiif
   >etc

Then when the user clicks on one of those options, we guide them to a page that looks like the TUTORIALS page today. A page with links to the tutorials about the topic they selected.

I think that makes a lot of sense. A lot cleaner that putting every tutorial on the side bar directly.
Thanks @kinow !

**Comment by kinow** [comment]
+1! And done!

**Comment by kinow** [comment]
Let's wait a few minutes for the site to be rebuild, then run the [W3C link verifier](https://validator.w3.org/checklink).

**Comment by kinow** [comment]
Phew! Quite a few links were being redirected and a few more got broken after the new structure of the tutorials.

@imoutsatsos have a look and feel free to close the ticket if that's looking OK now, otherwise let me know / or update what else is missing :D (I liked it more now! Another great idea by you!!!)

**Comment by imoutsatsos** [comment]
Looks great! It also helps us to focus on what new things to add to the tutorials. I know I have to add more things in the Active Choices section. Thank you so much @kinow .By the way we are just recovering from a Friday/Saturday [powerful storm](https://www.cnn.com/2018/03/02/us/weather-bomb-cyclone/index.html) that hit our area. I hope you are enjoying Summer in NZ!

**Comment by imoutsatsos** [comment]
Added Tutorials side panel list looks great!. Closing issue.

**Comment by kinow** [comment]
Perfect! Thanks for updating it! I heard about a storm in Ireland/UK, but nothing about US in the news here, besides the Oscars. Hope the weather gets a bit better soon.
