### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by kinow** [biouno/biouno.github.io#27]
@imoutsatsos take a look at the new favicon. I used the old one first (the one that said Bio1), but it looked too small...

So tried B1... which is also a vitamin import for humans... life-sciences.... _dad-joke level-up_!!!

![dad -joke](https://media.giphy.com/media/FUVSjcehhkUOQ/giphy.gif) 

Anyway, here's the preview.

![screenshot from 2019-03-02 00-25-09](https://user-images.githubusercontent.com/304786/53635622-97b2c000-3c82-11e9-941d-a77e128828df.png)

WDYT? Feel free to close the issue if it's good enough!

**Comment by imoutsatsos** [comment]
I like it! Nice idea! 
Now we need a small  graphic on the BioUno landing page to display on social sites when we share the BioUno project link. Most of them try to pick something from the page, but currently there is nothing there. We must be rather unique in not having 'eye candy' on our landing page ;-) But we can close this one!

**Comment by kinow** [comment]
Thanks @imoutsatsos !
