### ISSUE TITLE
Link to Blog Archive broken

### ISSUE THREAD

**Issue by imoutsatsos** [biouno/biouno.github.io#29]
http://biouno.org/archive.html link at the bottom of the 
http://biouno.org/blog/ page is broken

**Comment by kinow** [comment]
Tags was also broken. And categories :cry: 

Fixed tags and categories, but archives wasn't so simple.

It should actually get fixed if we upgrade the theme to the latest version, which is something that we should have done some time ago anyway: https://github.com/mmistakes/minimal-mistakes

**Comment by imoutsatsos** [comment]
Oh no! I did not think it was such major update!

**Comment by kinow** [comment]
Fixing page build. Something with symlinks...
