### ISSUE TITLE
Use remote theme

### ISSUE THREAD

**Issue by kinow** [biouno/biouno.github.io#31]
Seeing

>Your site is having problems building: A file was included in _pages/archive.md that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/en/articles/page-build-failed-file-is-a-symlink. 

After pushing the latest changes. Funny that it worked on my repository kinow.github.io. From the docs of the theme, they say

>100% compatible with GitHub Pages when used as a remote theme.

So let's try to use it as a remote theme.

**Comment by kinow** [comment]
Phew. Finally looks to be working. What a ride it was to update this theme. Time to rest a bit now :zzz:

**Comment by imoutsatsos** [comment]
Yes get some rest 'code warrior'!
